server:
  port: 9001
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: oauth  #路由的id,建议与服务名一致
          uri: lb://oauth  #匹配后提供服务的路由地址
          predicates:
            - Path=/oauth/** #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1 #去除security进行路由匹配
        - id: netty  #路由的id,建议与服务名一致
          uri: lb://netty  #匹配后提供服务的路由地址
          predicates:
            - Path=/netty/** #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1 #去除netty进行路由匹配
        - id: user  #路由的id,建议与服务名一致
          uri: lb://user  #匹配后提供服务的路由地址
          predicates:
            - Path=/user/** #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1 #去除netty进行路由匹配
        - id: search  #路由的id,建议与服务名一致
          uri: lb://search  #匹配后提供服务的路由地址
          predicates:
            - Path=/search/** #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1 #去除netty进行路由匹配
