server:
  port: 9008
spring:
  application:
    name: skill
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 192.168.146.130
    port: 5672
    username: guest
    password: guest
#自己定义主题名称
mytopic: item-topic
